name: Update Data
on:
  schedule:
    # 18:07 UTC every day
    # 23:37 IST every day
    - cron: '7 18 * * *'
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Update data
      run: make all
      id: update_data
    # Only tag if we're running on the scheduled job
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update ISIN Data
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: "*.csv"
        status_options: '--untracked-files=no'
        tagging_message: "v${{ steps.update_data.outputs.version }}"
    - name: Create Release
      run: git diff --ignore-all-space -U0 HEAD^ *.csv|egrep -oe '^([+-]IN\w{10})' | gh release create "v${{ steps.update_data.outputs.version }}" --notes-file -
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
