name: Update Data
on:
  push:
  # Run this on Sundays because NSDL won't add new things then
  schedule:
    # 8:07 UTC every Sunday
    # 13:37 IST every Sunday
    - cron: '7 8 * * 0'
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        # Versioning is current date
        format: "YYYY.M.D"
    - name: Update data
      run: ./fetch.sh
    # Only tag if we're running on the scheduled job
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'schedule' }}
      with:
        commit_message: Update ISIN Data
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: "*.csv"
        status_options: '--untracked-files=no'
        tagging_message: "v${{ steps.current-time.outputs.formattedTime }}"
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'push' }}
      with:
        commit_message: Update ISIN Data
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: "*.csv"
        status_options: '--untracked-files=no'
